name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive

      # - name: Install C++ dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #       libeigen3-dev \
      #       libboost-all-dev \
      #       nlohmann-json3-dev \

      # # - name: Create build directory
      # #   run: mkdir -p build

      - name: Enable brew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Install C++ dependencies
        run: |
          brew install boost eigen nlohmann-json msgpack-cxx doctest

      - name: Configure with CMake
        run: cmake -S . -B build -DPGM_IO_ENABLE_DEV_BUILD=ON

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build -V
